### ISSUE TITLE
Separate scanning for outputs and generating the keys as receiver

### ISSUE THREAD

**Issue by Sosthene00** [cygnet3/rust-silentpayments#34]
As a receiver, you need to store the keys you derive from transactions that pay you, and retrieve the rigth key when spending. While this is mostly the wallet's concern, silent payment doesn't fit very well with the traditional model of BIP32 key derivation, and even less with the most advanced descriptor based model. 

Also the problem would be even worse with hardware wallets, that for obvious security reasons won't allow importing private keys. 

One way to make this problem easier to handle for wallets would be to not store the private keys at all, since it can be rather easily derived on the fly with some public data and the traditional bip32 wallet. 

`scan_transaction` should rather return the pubkeys than the private keys, then wallets could adopt different strategies to keep track of those outputs best suited to their internal and key storing strategies. The key generation would only happen at spend time, and keys could then be discarded immediately. 

Another way to handle this would be to optionaly return the private keys with some flag passed to the existing `scan_transaction`, or to totally let this choice to the caller.

**Comment by vincenzopalazzo** [comment]
This is a nice point!

I will vote for the following option, or make two different method

>Another way to handle this would be to optionaly return the private keys with some flag passed to the existing scan_transaction, or to totally let this choice to the caller.

**Comment by Sosthene00** [comment]
Actually @cygnet3 had a better idea than that, the best would be to not return either key, but only the tweak. Closing this and opening another issue to discuss this
