### ISSUE TITLE
Modifying the `Receiver` to return only the tweak instead of whole private keys

### ISSUE THREAD

**Issue by Sosthene00** [cygnet3/rust-silentpayments#35]
In #34 we raised an issue with returning the whole spending private keys when scanning transactions for our outputs. It made key storage and retrieval complicated for wallets and signers, especially hardware wallets that most of the time wouldn't allow importing private keys. It also implied that the `Receiver` must keep the spend private key, which would also be a huge problem when working with hww.

Instead of flagging the pubkeys that belong to us with scanning and having another method of the `Receiver` to actually generate and return the private key, @cygnet3 proposed to only compute and return the tweaks when we can find keys that belong to us.

It has the same advantages than separating scanning and key generation, but also mean that the `Receiver` doesn't need to keep the spend private key anymore (but the problem to extract the scan private key from a hww still exists).

Actually, could we also take the scan_privkey out of the `Receiver`? It means that we will need the signer to perform ECDH before calling `scan_transaction` with the shared secret instead of the tweak data, but since that's already what we're doing for generating the secret on the side of the Sender maybe it makes more sense after all

**Comment by cygnet3** [comment]
> Actually, could we also take the scan_privkey out of the `Receiver`? It means that we will need the signer to perform ECDH before calling `scan_transaction` with the shared secret instead of the tweak data, but since that's already what we're doing for generating the secret on the side of the Sender maybe it makes more sense after all

Hmm, taking out the scan_privkey also sounds quite interesting indeed. And I like the idea of making it mirror the logic on the sender side too, where we also assume a pre-computed shared secret.
In all honesty, I think it is a bit 'uglier' on the sender side to expect the user to pass in the pre-computed secret, because this already requires the user to 'decode' a SP address first (you need the B_scan).

We should be revisit how we do this on both sender and receiver side. I'll create a separate issue for that later.

**Comment by Sosthene00** [comment]
I don't think that's much of an issue, decoding the B_spend from an address is pretty straightforward and if we want to be able to work with most signers and especially hww at some points we don't have much choice anyway.

**Comment by cygnet3** [comment]
Hmm, I'm not sure if I understand why it would make working with signers easier. I made an issue for it (#38), let's discuss further there.
